twoloophiggsmassdiags[[1]]={
{WoSSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {hh, i4, 1}},{{-1/2,WfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Ah, i3, 1}, {Ah, i4, 1}},{{-1/4,WfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {hh, i4, 1}},{{-1/4,WfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Hp, i3, 1}, {conj[Hp], i4, 1}},{{-1/2,WfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1/4,WfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {hh, i3, 1}, {Hp, i4, 1}},{{-1,WfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {hh, i3, 1}, {ss, i4, 1}},{{-1/2,WfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}}}
}},
{XoSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, Ah, Ah]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {hh, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Hp, i3, 1}},{{1/2,XfSSS,{0, 0}}},{{{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, Hp, conj[Hp]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {ss, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, ss, ss]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Ah, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[Ah, Ah, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, hh, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Hp, i3, 1}},{{1/2,XfSSS,{0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {ss, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Ah, i3, 1}},{{1/2,XfSSS,{0, 0}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[Ah, Ah, Hp, conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {hh, i3, 1}},{{1/2,XfSSS,{0, 0}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[hh, hh, Hp, conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}},{{1,XfSSS,{0, 0}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[Hp, Hp, conj[Hp], conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {ss, i3, 1}},{{1/2,XfSSS,{0, 0}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[Hp, ss, ss, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {Ah, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[hh, hh, ss, ss]}, {{}, C[Ah, Ah, ss, ss]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {hh, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[hh, hh, ss, ss]}, {{}, C[hh, hh, ss, ss]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {Hp, i3, 1}},{{1/2,XfSSS,{0, 0}}},{{{}, C[hh, hh, ss, ss]}, {{}, C[Hp, ss, ss, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}},{{1/4,XfSSS,{0, 0}}},{{{}, C[hh, hh, ss, ss]}, {{}, C[ss, ss, ss, ss]}}}
}},
{YoSSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Ah, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, Ah, Ah]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {hh, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Hp, i4, 1}},{{-1,YfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, Hp, conj[Hp]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {ss, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, ss, ss]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Ah, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[Ah, Ah, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {hh, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Hp, i4, 1}},{{-1,YfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {ss, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {Ah, i4, 1}},{{-1,YfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[Ah, Ah, Hp, conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {hh, i4, 1}},{{-1,YfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, hh, Hp, conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {Hp, i4, 1}},{{-2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[Hp, Hp, conj[Hp], conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {ss, i4, 1}},{{-1,YfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[Hp, ss, ss, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {Ah, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[Ah, Ah, ss, ss]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {hh, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, hh, ss, ss]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {Hp, i4, 1}},{{-1,YfSSSS,{0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[Hp, ss, ss, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[ss, ss, ss, ss]}}}
}},
{ZoSSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Ah, i4, 1}},{{-1/4,ZfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, Ah, Ah]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {hh, i3, 1}, {hh, i4, 1}},{{-1/2,ZfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[hh, hh, hh]}, {{}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Hp, i3, 1}, {conj[Hp], i4, 1}},{{-1,ZfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[Ah, Ah, Hp, conj[Hp]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1/2,ZfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[hh, ss, ss]}, {{}, C[Ah, Ah, ss, ss]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {hh, i4, 1}},{{-1/4,ZfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Hp, i3, 1}, {conj[Hp], i4, 1}},{{-1,ZfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1/2,ZfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, ss, ss]}, {{}, C[hh, hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {conj[Hp], i4, 1}},{{-1,ZfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[Hp, Hp, conj[Hp], conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1,ZfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, ss, ss]}, {{}, C[Hp, ss, ss, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1/4,ZfSSSS,{0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[ss, ss, ss, ss]}}}
}},
{SoSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {hh, i3, 1}},{{1/2,SfSSS,{0, 0}}},{{{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}},{{1/6,SfSSS,{0, 0}}},{{{}, C[hh, hh, hh, hh]}, {{}, C[hh, hh, hh, hh]}}},
{{{hh, i1, 1}, {Hp, i2, 1}, {conj[Hp], i3, 1}},{{1,SfSSS,{0, 0}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[hh, hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {ss, i2, 1}, {ss, i3, 1}},{{1/2,SfSSS,{0, 0}}},{{{}, C[hh, hh, ss, ss]}, {{}, C[hh, hh, ss, ss]}}}
}},
{UoSSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {hh, i4, 1}},{{-2,UfSSSS,{0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Ah, i3, 1}, {Ah, i4, 1}},{{-1,UfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[Ah, Ah, hh, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {hh, i4, 1}},{{-1,UfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh, hh]}, {{}, C[hh, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Hp, i3, 1}, {conj[Hp], i4, 1}},{{-2,UfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {ss, i3, 1}, {ss, i4, 1}},{{-1,UfSSSS,{0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, ss, ss]}, {{}, C[hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {hh, i3, 1}, {Hp, i4, 1}},{{-4,UfSSSS,{0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {hh, i3, 1}, {ss, i4, 1}},{{-2,UfSSSS,{0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, hh, ss, ss]}, {{}, C[hh, ss, ss]}}}
}},
{VoSSSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Ah, i4, 1}, {hh, i5, 1}},{{1,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Ah, i4, 1}, {Ah, i5, 1}},{{1/2,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {hh, i4, 1}, {hh, i5, 1}},{{1/2,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Hp, i4, 1}, {conj[Hp], i5, 1}},{{1,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {ss, i4, 1}, {ss, i5, 1}},{{1/2,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {hh, i4, 1}, {conj[Hp], i5, 1}},{{2,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {hh, i4, 1}, {ss, i5, 1}},{{1,VfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}}}
}},
{MoSSSSS,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Ah, i4, 1}, {hh, i5, 1}},{{1/2,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 1}, {hh, i2, 1}, {Ah, i3, 1}, {hh, i4, 1}, {Ah, i5, 1}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[Ah, Ah, hh]}, {{}, C[hh, hh, hh]}, {{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {hh, i4, 1}, {hh, i5, 1}},{{1/2,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}}},
{{{hh, i1, 1}, {Hp, i2, 1}, {hh, i3, 1}, {conj[Hp], i4, 1}, {Hp, i5, 1}},{{2,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{hh, i1, 1}, {ss, i2, 1}, {hh, i3, 1}, {ss, i4, 1}, {ss, i5, 1}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {conj[Hp], i3, 1}, {Hp, i4, 1}, {hh, i5, 1}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}}},
{{{ss, i1, 1}, {ss, i2, 1}, {ss, i3, 1}, {ss, i4, 1}, {hh, i5, 1}},{{1/2,MfSSSSS,{0, 0, 0, 0}}},{{{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}, {{}, C[hh, ss, ss]}}}
}},
{WoSSFF,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3/2*Mass[Fd,i3]*Mass[bar[Fd],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{}, C[Ah, Ah, hh, hh]}, {{{bar[Fd], i4}, {Fd, i3}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}}, C[Ah, Fd, bar[Fd]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1/2*Mass[Fe,i3]*Mass[bar[Fe],i4],WfSSFbFb,{0, L, L}},{-1/2,WfSSFF,{0, L, R}}},{{{}, C[Ah, Ah, hh, hh]}, {{{bar[Fe], i4}, {Fe, i3}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}}, C[Ah, Fe, bar[Fe]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3/2*Mass[Fu,i3]*Mass[bar[Fu],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{}, C[Ah, Ah, hh, hh]}, {{{bar[Fu], i4}, {Fu, i3}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}}, C[Ah, Fu, bar[Fu]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3/2*Mass[Fd,i3]*Mass[bar[Fd],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{}, C[hh, hh, hh, hh]}, {{{bar[Fd], i4}, {Fd, i3}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1/2*Mass[Fe,i3]*Mass[bar[Fe],i4],WfSSFbFb,{0, L, L}},{-1/2,WfSSFF,{0, L, R}}},{{{}, C[hh, hh, hh, hh]}, {{{bar[Fe], i4}, {Fe, i3}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}}, C[Fe, hh, bar[Fe]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3/2*Mass[Fu,i3]*Mass[bar[Fu],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{}, C[hh, hh, hh, hh]}, {{{bar[Fu], i4}, {Fu, i3}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Fu, i3, 3}, {bar[Fd], i4, 3}},{{-3*Mass[Fu,i3]*Mass[bar[Fd],i4],WfSSFbFb,{0, L, L}},{-3,WfSSFF,{0, L, R}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{{bar[Fd], i4}, {Fu, i3}}, C[Fu, bar[Fd], conj[Hp]]}, {{{bar[Fu], i3}, {Fd, i4}}, C[Fd, Hp, bar[Fu]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Fv, i3, 3}, {bar[Fe], i4, 3}},{{-1*Mass[Fv,i3]*Mass[bar[Fe],i4],WfSSFbFb,{0, L, L}},{-1,WfSSFF,{0, L, R}}},{{{}, C[hh, hh, Hp, conj[Hp]]}, {{{bar[Fe], i4}, {Fv, i3}}, C[Fv, bar[Fe], conj[Hp]]}, {{{bar[Fv], i3}, {Fe, i4}}, C[Fe, Hp, bar[Fv]]}}}
}},
{MoFFFFS,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {bar[Fd], i3, 3}, {Fd, i4, 3}, {Ah, i5, 1}},{{3*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fd],i2]*Mass[bar[Fd],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fd],i2]*Mass[Fd,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fd], i3}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i3}}, C[Ah, Fd, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {bar[Fd], i3, 3}, {Fd, i4, 3}, {hh, i5, 1}},{{3*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fd],i2]*Mass[bar[Fd],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fd],i2]*Mass[Fd,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fd], i3}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i2}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i3}}, C[Fd, hh, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fu], i2, 3}, {bar[Fd], i3, 3}, {Fu, i4, 3}, {conj[Hp], i5, 1}},{{3*Mass[Fd,i1]*Mass[bar[Fu],i2]*Mass[bar[Fd],i3]*Mass[Fu,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fu],i2]*Mass[bar[Fd],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fu],i2]*Mass[Fu,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fd],i3]*Mass[Fu,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fd], i3}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fu], i2}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fd], i1}, {Fu, i2}}, C[Fu, bar[Fd], conj[Hp]]}, {{{bar[Fu], i4}, {Fd, i3}}, C[Fd, Hp, bar[Fu]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {bar[Fe], i3, 3}, {Fe, i4, 3}, {Ah, i5, 1}},{{1*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFbFbFbFbS,{L, L, L, L}},{2*Mass[bar[Fe],i2]*Mass[bar[Fe],i3],MfFFbFbFS,{L, R, R, L}},{2*Mass[bar[Fe],i2]*Mass[Fe,i4],MfFFbFFbS,{L, R, R, R}},{2*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFFFbFbS,{L, L, R, L}},{1,MfFFFFS,{L, L, R, R}}},{{{{bar[Fe], i3}, {Fe, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i4}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i3}}, C[Ah, Fe, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {bar[Fe], i3, 3}, {Fe, i4, 3}, {hh, i5, 1}},{{1*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFbFbFbFbS,{L, L, L, L}},{2*Mass[bar[Fe],i2]*Mass[bar[Fe],i3],MfFFbFbFS,{L, R, R, L}},{2*Mass[bar[Fe],i2]*Mass[Fe,i4],MfFFbFFbS,{L, R, R, R}},{2*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFFFbFbS,{L, L, R, L}},{1,MfFFFFS,{L, L, R, R}}},{{{{bar[Fe], i3}, {Fe, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i4}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i2}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i3}}, C[Fe, hh, bar[Fe]]}}},
{{{Fu, i1, 3}, {bar[Fd], i2, 3}, {bar[Fu], i3, 3}, {Fd, i4, 3}, {Hp, i5, 1}},{{3*Mass[Fu,i1]*Mass[bar[Fd],i2]*Mass[bar[Fu],i3]*Mass[Fd,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fd],i2]*Mass[bar[Fu],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fd],i2]*Mass[Fd,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fu],i3]*Mass[Fd,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fu], i3}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fd], i2}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fu], i1}, {Fd, i2}}, C[Fd, Hp, bar[Fu]]}, {{{bar[Fd], i4}, {Fu, i3}}, C[Fu, bar[Fd], conj[Hp]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {bar[Fu], i3, 3}, {Fu, i4, 3}, {Ah, i5, 1}},{{3*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fu],i2]*Mass[bar[Fu],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fu],i2]*Mass[Fu,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fu], i3}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i3}}, C[Ah, Fu, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {bar[Fu], i3, 3}, {Fu, i4, 3}, {hh, i5, 1}},{{3*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fu],i2]*Mass[bar[Fu],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fu],i2]*Mass[Fu,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fu], i3}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i2}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i3}}, C[Fu, hh, bar[Fu]]}}}
}},
{MoSFSFF,{
{{{Ah, i1, 1}, {Fd, i2, 3}, {Ah, i3, 1}, {bar[Fd], i4, 3}, {Fd, i5, 3}},{{6*Mass[Fd,i2]*Mass[bar[Fd],i4]*Mass[Fd,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fd],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fd,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[Ah, Ah, hh]}, {{{bar[Fd], i4}, {Fd, i2}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i5}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i5}, {Fd, i4}}, C[Ah, Fd, bar[Fd]]}}},
{{{Ah, i1, 1}, {Fe, i2, 3}, {Ah, i3, 1}, {bar[Fe], i4, 3}, {Fe, i5, 3}},{{2*Mass[Fe,i2]*Mass[bar[Fe],i4]*Mass[Fe,i5],MfSFbSFbFb,{0, L, L, L}},{4*Mass[bar[Fe],i4],MfSFSFbF,{0, L, R, L}},{2*Mass[Fe,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[Ah, Ah, hh]}, {{{bar[Fe], i4}, {Fe, i2}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i5}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i5}, {Fe, i4}}, C[Ah, Fe, bar[Fe]]}}},
{{{Ah, i1, 1}, {Fu, i2, 3}, {Ah, i3, 1}, {bar[Fu], i4, 3}, {Fu, i5, 3}},{{6*Mass[Fu,i2]*Mass[bar[Fu],i4]*Mass[Fu,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fu],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fu,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[Ah, Ah, hh]}, {{{bar[Fu], i4}, {Fu, i2}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i5}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i5}, {Fu, i4}}, C[Ah, Fu, bar[Fu]]}}},
{{{hh, i1, 1}, {Fd, i2, 3}, {hh, i3, 1}, {bar[Fd], i4, 3}, {Fd, i5, 3}},{{6*Mass[Fd,i2]*Mass[bar[Fd],i4]*Mass[Fd,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fd],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fd,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[hh, hh, hh]}, {{{bar[Fd], i4}, {Fd, i2}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i5}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i5}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}}},
{{{hh, i1, 1}, {Fe, i2, 3}, {hh, i3, 1}, {bar[Fe], i4, 3}, {Fe, i5, 3}},{{2*Mass[Fe,i2]*Mass[bar[Fe],i4]*Mass[Fe,i5],MfSFbSFbFb,{0, L, L, L}},{4*Mass[bar[Fe],i4],MfSFSFbF,{0, L, R, L}},{2*Mass[Fe,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[hh, hh, hh]}, {{{bar[Fe], i4}, {Fe, i2}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i5}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i5}, {Fe, i4}}, C[Fe, hh, bar[Fe]]}}},
{{{hh, i1, 1}, {Fu, i2, 3}, {hh, i3, 1}, {bar[Fu], i4, 3}, {Fu, i5, 3}},{{6*Mass[Fu,i2]*Mass[bar[Fu],i4]*Mass[Fu,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fu],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fu,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[hh, hh, hh]}, {{{bar[Fu], i4}, {Fu, i2}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i5}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i5}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}}},
{{{Hp, i1, 1}, {Fd, i2, 3}, {conj[Hp], i3, 1}, {bar[Fd], i4, 3}, {Fu, i5, 3}},{{6*Mass[Fd,i2]*Mass[bar[Fd],i4]*Mass[Fu,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fd],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fu,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[hh, Hp, conj[Hp]]}, {{{bar[Fd], i4}, {Fd, i2}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i2}, {Fu, i5}}, C[Fu, bar[Fd], conj[Hp]]}, {{{bar[Fu], i5}, {Fd, i4}}, C[Fd, Hp, bar[Fu]]}}},
{{{Hp, i1, 1}, {Fe, i2, 3}, {conj[Hp], i3, 1}, {bar[Fe], i4, 3}, {Fv, i5, 3}},{{2*Mass[Fe,i2]*Mass[bar[Fe],i4]*Mass[Fv,i5],MfSFbSFbFb,{0, L, L, L}},{4*Mass[bar[Fe],i4],MfSFSFbF,{0, L, R, L}},{2*Mass[Fv,i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[hh, Hp, conj[Hp]]}, {{{bar[Fe], i4}, {Fe, i2}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i2}, {Fv, i5}}, C[Fv, bar[Fe], conj[Hp]]}, {{{bar[Fv], i5}, {Fe, i4}}, C[Fe, Hp, bar[Fv]]}}},
{{{Hp, i1, 1}, {bar[Fu], i2, 3}, {conj[Hp], i3, 1}, {Fu, i4, 3}, {bar[Fd], i5, 3}},{{6*Mass[bar[Fu],i2]*Mass[Fu,i4]*Mass[bar[Fd],i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[Fu,i4],MfSFSFbF,{0, L, R, L}},{6*Mass[bar[Fd],i5],MfSFSFFb,{0, L, R, R}}},{{{}, C[hh, Hp, conj[Hp]]}, {{{bar[Fu], i2}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fd], i5}, {Fu, i2}}, C[Fu, bar[Fd], conj[Hp]]}, {{{bar[Fu], i4}, {Fd, i5}}, C[Fd, Hp, bar[Fu]]}}}
}},
{VoSSSFF,{
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Fd, i4, 3}, {bar[Fd], i5, 3}},{{3*Mass[Fd,i4]*Mass[bar[Fd],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{{bar[Fd], i5}, {Fd, i4}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i5}}, C[Ah, Fd, bar[Fd]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Fe, i4, 3}, {bar[Fe], i5, 3}},{{1*Mass[Fe,i4]*Mass[bar[Fe],i5],VfSSSFbFb,{0, 0, L, L}},{1,VfSSSFF,{0, 0, L, R}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{{bar[Fe], i5}, {Fe, i4}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i5}}, C[Ah, Fe, bar[Fe]]}}},
{{{Ah, i1, 1}, {Ah, i2, 1}, {Ah, i3, 1}, {Fu, i4, 3}, {bar[Fu], i5, 3}},{{3*Mass[Fu,i4]*Mass[bar[Fu],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{}, C[Ah, Ah, hh]}, {{}, C[Ah, Ah, hh]}, {{{bar[Fu], i5}, {Fu, i4}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i5}}, C[Ah, Fu, bar[Fu]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Fd, i4, 3}, {bar[Fd], i5, 3}},{{3*Mass[Fd,i4]*Mass[bar[Fd],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{{bar[Fd], i5}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i5}}, C[Fd, hh, bar[Fd]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Fe, i4, 3}, {bar[Fe], i5, 3}},{{1*Mass[Fe,i4]*Mass[bar[Fe],i5],VfSSSFbFb,{0, 0, L, L}},{1,VfSSSFF,{0, 0, L, R}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{{bar[Fe], i5}, {Fe, i4}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i5}}, C[Fe, hh, bar[Fe]]}}},
{{{hh, i1, 1}, {hh, i2, 1}, {hh, i3, 1}, {Fu, i4, 3}, {bar[Fu], i5, 3}},{{3*Mass[Fu,i4]*Mass[bar[Fu],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{}, C[hh, hh, hh]}, {{}, C[hh, hh, hh]}, {{{bar[Fu], i5}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i5}}, C[Fu, hh, bar[Fu]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {Fd, i4, 3}, {bar[Fu], i5, 3}},{{6*Mass[Fd,i4]*Mass[bar[Fu],i5],VfSSSFbFb,{0, 0, L, L}},{6,VfSSSFF,{0, 0, L, R}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{{bar[Fu], i5}, {Fd, i4}}, C[Fd, Hp, bar[Fu]]}, {{{bar[Fd], i4}, {Fu, i5}}, C[Fu, bar[Fd], conj[Hp]]}}},
{{{Hp, i1, 1}, {conj[Hp], i2, 1}, {Hp, i3, 1}, {Fe, i4, 3}, {bar[Fv], i5, 3}},{{2*Mass[Fe,i4]*Mass[bar[Fv],i5],VfSSSFbFb,{0, 0, L, L}},{2,VfSSSFF,{0, 0, L, R}}},{{{}, C[hh, Hp, conj[Hp]]}, {{}, C[hh, Hp, conj[Hp]]}, {{{bar[Fv], i5}, {Fe, i4}}, C[Fe, Hp, bar[Fv]]}, {{{bar[Fe], i4}, {Fv, i5}}, C[Fv, bar[Fe], conj[Hp]]}}}
}},
{VoFFFFS,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}, {Ah, i5, 1}},{{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fd,i1]*Mass[Fd,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fd],i2]*Mass[Fd,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fd], i2}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}}, C[Ah, Fd, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}, {hh, i5, 1}},{{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fd,i1]*Mass[Fd,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fd],i2]*Mass[Fd,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fd], i2}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i2}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}}, C[Fd, hh, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {bar[Fu], i4, 3}, {Hp, i5, 1}},{{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3]*Mass[bar[Fu],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fd,i1]*Mass[Fd,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fu],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fd],i2]*Mass[Fd,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fd,i3]*Mass[bar[Fu],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fd], i2}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fu], i4}, {Fd, i2}}, C[Fd, Hp, bar[Fu]]}, {{{bar[Fd], i3}, {Fu, i4}}, C[Fu, bar[Fd], conj[Hp]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}, {Ah, i5, 1}},{{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFbFbFbFbS,{L, L, L, L}},{4*Mass[Fe,i1]*Mass[Fe,i3],VfFbFFbFS,{L, L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i4],VfFbFFFbS,{L, L, R, R}},{2*Mass[bar[Fe],i2]*Mass[Fe,i3],VfFFbFbFS,{L, R, L, R}},{4*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFFFbFbS,{L, R, R, R}},{2,VfFFFFS,{L, R, R, L}}},{{{{bar[Fe], i2}, {Fe, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}}, C[Ah, Fe, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}, {hh, i5, 1}},{{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFbFbFbFbS,{L, L, L, L}},{4*Mass[Fe,i1]*Mass[Fe,i3],VfFbFFbFS,{L, L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i4],VfFbFFFbS,{L, L, R, R}},{2*Mass[bar[Fe],i2]*Mass[Fe,i3],VfFFbFbFS,{L, R, L, R}},{4*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFFFbFbS,{L, R, R, R}},{2,VfFFFFS,{L, R, R, L}}},{{{{bar[Fe], i2}, {Fe, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i2}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}}, C[Fe, hh, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {bar[Fv], i4, 3}, {Hp, i5, 1}},{{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3]*Mass[bar[Fv],i4],VfFbFbFbFbS,{L, L, L, L}},{4*Mass[Fe,i1]*Mass[Fe,i3],VfFbFFbFS,{L, L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fv],i4],VfFbFFFbS,{L, L, R, R}},{2*Mass[bar[Fe],i2]*Mass[Fe,i3],VfFFbFbFS,{L, R, L, R}},{4*Mass[Fe,i3]*Mass[bar[Fv],i4],VfFFFbFbS,{L, R, R, R}},{2,VfFFFFS,{L, R, R, L}}},{{{{bar[Fe], i2}, {Fe, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fv], i4}, {Fe, i2}}, C[Fe, Hp, bar[Fv]]}, {{{bar[Fe], i3}, {Fv, i4}}, C[Fv, bar[Fe], conj[Hp]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}, {Ah, i5, 1}},{{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fu,i1]*Mass[Fu,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fu],i2]*Mass[Fu,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fu], i2}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}}, C[Ah, Fu, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}, {hh, i5, 1}},{{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fu,i1]*Mass[Fu,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fu],i2]*Mass[Fu,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fu], i2}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i2}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}}, C[Fu, hh, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {bar[Fd], i4, 3}, {conj[Hp], i5, 1}},{{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3]*Mass[bar[Fd],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fu,i1]*Mass[Fu,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fd],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fu],i2]*Mass[Fu,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fu,i3]*Mass[bar[Fd],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fu], i2}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fd], i4}, {Fu, i2}}, C[Fu, bar[Fd], conj[Hp]]}, {{{bar[Fu], i3}, {Fd, i4}}, C[Fd, Hp, bar[Fu]]}}}
}},
{GoFFFFV,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}},{{4,GfFFV,{L, R, 0, 0}},{4*Mass[Fd,i1]*Mass[bar[Fd],i2],GfFbFbV,{L, L, 0, 0}}},{{{{bar[Fd], i2}, {Fd, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i2}}, C[Fd, hh, bar[Fd]]}, {{}, g3}, {{}, g3}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}},{{4,GfFFV,{L, R, 0, 0}},{4*Mass[Fu,i1]*Mass[bar[Fu],i2],GfFbFbV,{L, L, 0, 0}}},{{{{bar[Fu], i2}, {Fu, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i2}}, C[Fu, hh, bar[Fu]]}, {{}, g3}, {{}, g3}}}
}}
}
